In [1]:
import torch 

In [2]:
# Define w = 2 and b = -1 for y = wx + b 
w = torch.tensor(2.0, requires_grad=True) 
b = torch.tensor(-1.0, requires_grad=True) 

In [3]:
# Define the function `forward(x, w, b)` makes the prediction 
def forward(x): 
    y_hat = w * x + b 
    return y_hat

In [6]:
# Predict at x = 1
x = torch.tensor([[1.0]])
y_hat = forward(x) 
print(f"Prediction: {y_hat}")

Prediction: tensor([[1.]], grad_fn=<AddBackward0>)


In [7]:
# Predict multiple inputs 
# Create x Tensor and check the shape of the x Tensor 
x = torch.tensor([[1.0], [2.0]]) 
print(f"Shape: {x.shape}")

Shape: torch.Size([2, 1])


In [8]:
y_hat = forward(x) 
print(f"Prediction for multiple inputs: {y_hat}")

Prediction for multiple inputs: tensor([[1.],
        [3.]], grad_fn=<AddBackward0>)


In [9]:
# Can be done with the Linear class 
from torch.nn import Linear 
# Set random seed 
torch.manual_seed(1) 


In [11]:
# Create Linear Regression Model and print out the parameters (parmeters are randomly created) 
lr = Linear(in_features=1, out_features=1, bias=True) 
print(f"Parameters w and b are: {list(lr.parameters())}")

Parameters w and b are: [Parameter containing:
tensor([[-0.1939]], requires_grad=True), Parameter containing:
tensor([0.4694], requires_grad=True)]


In [13]:
# `state_dict` method returns a python dictionary object corresponding to the layers of each parameter tensor 
print(f"Dictionary: {lr.state_dict()}")

Dictionary: OrderedDict([('weight', tensor([[-0.1939]])), ('bias', tensor([0.4694]))])


In [17]:
# Make single prediciton at x = [[1.0]] 
x = torch.tensor([[1.0]]) 
y_hat = lr(x) 
print(f"Prediction: {y_hat}")

Prediction: tensor([[0.2755]], grad_fn=<AddmmBackward0>)


In [18]:
# Multiple predictions 
x = torch.tensor([[1.0], [2.0]]) 
y_hat = lr(x) 
print(f"Multiple prediction: {y_hat}") 

Multiple prediction: tensor([[0.2755],
        [0.0816]], grad_fn=<AddmmBackward0>)


In [19]:
# Building custom modules 
from torch import nn 

In [20]:
# Define the class 

class LR(nn.Module): 
    # constructor 
    def __init__(self, input_size, output_size): 
        # Inherit from parent 
        super(LR, self).__init__() 
        self.linear = nn.Linear(input_size, output_size) 
    
    # Prediction function 
    def forward(self, x): 
        out = self.linear(x) 
        return out 
    

In [21]:
# Create a linear regression model using the custom module 
lr = LR(input_size=1, output_size=1) 
print(f"parameters: {list(lr.parameters())}") 
print(f"Linear Model: {lr.linear}")

parameters: [Parameter containing:
tensor([[-0.9414]], requires_grad=True), Parameter containing:
tensor([0.5997], requires_grad=True)]
Linear Model: Linear(in_features=1, out_features=1, bias=True)
